### ISSUE TITLE
Develop branch will not launch

### ISSUE THREAD

**Issue by RuthDVerizon** [openbaton/NFVO#178]
When launching the program from the develop branch as of commit aa2b1f4965be792524dca0347a60c79e5ae66295 now see error 

```
2017-07-24 21:41:30.762 ERROR 4705 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at org.openbaton.nfvo.main.Application.main(Application.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:98)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:75)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:378)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:155)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:157)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
        ... 13 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setFilterChainProxySecurityConfigurer' parameter 1; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfig': Unsatisfied dependency expressed through method 'setContentNegotationStrategy' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'interceptorConfiguration': Unsatisfied dependency expressed through field 'authorizeInterceptor'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizeInterceptor': Unsatisfied dependency expressed through field 'userManagement'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userManagement': Unsatisfied dependency expressed through field 'userRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Cannot create inner bean '(inner bean)#3a289a78' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#3a289a78': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'flywayConfig': Unsatisfied dependency expressed through field 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver
```

with further repeated errors.  Commit 0cb94772af9b4938518c13028c687b8e32723bfe still runs successfully.

**Comment by gc4rella** [comment]
Hi @RuthDVerizon, we switched to the mariadb connector for mysql, as it has a license more open than the mysql one. All you need to do is to update your openbaton properties file, following line: 
`spring.datasource.driver-class-name=org.mariadb.jdbc.Driver`

**Comment by RuthDVerizon** [comment]
Hi @gc4rella, the openbaton.properties file that is being downloaded with the bootstrap file still has `spring.datasource.driver-class-name=com.mysql.jdbc.Driver` in it.  Can that be updated?

**Comment by gc4rella** [comment]
Hi @RuthDVerizon, yes, this is something we are working on as part of the release process. are you using the bootstrap for installing the development version? 

@flaviomu can provide more details about dates.

**Comment by RuthDVerizon** [comment]
@gc4rella @flaviomu 

Yes I used the bootstrap method to install the develop code so that I could look at the discussion concerning issue 118.  I can install the code separately but do not currently have another method to install the database and config files?  Is there a better means to do so?

**Comment by gc4rella** [comment]
@RuthDVerizon, @flaviomu is already working on it. Bootstrap should work again by today, latest tomorrow

**Comment by flaviomu** [comment]
Hi @RuthDVerizon , you can install mysql and configure it for Open Baton with the following command:
`sh <(curl -s http://get.openbaton.org/bootstrap) enable-persistence`
It expects that the NFVO properties file (`openbaton.properties` or `openbaton-nfvo.properties`) is in the default properties files directory (`/etc/openbaton/`)

**Comment by RuthDVerizon** [comment]
Hi @flaviomu , before I trash my baton box and start over, have you changed the contents of the /etc/openbaton/openbaton.properties file?  Using `sh <(curl -s http://get.openbaton.org/bootstrap)` and choosing the enable persistence option configures it to use that file but that file is set with the old value.

Thanks

**Comment by gc4rella** [comment]
Hi @RuthDVerizon could you please provide the full (bootstrap) command you are using for downloading the develop version of OB?

**Comment by RuthDVerizon** [comment]
`sh <(curl -s http://get.openbaton.org/bootstrap)`
<ENTER> - get develop
<mgmt ip address>
<ENTER> - default port
<ENTER> - do not do HTTPS
<ENTER> - persist through mysql
Mysql root password twice through GUI
<Mysql user>
<Mysql password>
<Mysql root password>
<Admin user name> - I think, does't show in my notes
<Admin password>
Install vnfm generic
Do not install fault management
Do not install auto scaling engine
Do not install network slicing engine

**Comment by gc4rella** [comment]
OK, please go ahead and do a new installation as it should work now. that file has been updated on the develop branch therefore you should not find that issue. In addition, I suggest you to make use of the config file option so that you can repeat the whole installation in a non-interactive way. if you want we can provide you some help with that.

**Comment by RuthDVerizon** [comment]
Doing it without the config file would be awesome!

**Comment by gc4rella** [comment]
OK, will provide you some more info via mail!

**Comment by RuthDVerizon** [comment]
Now able to download develop code using bootstrap using config file and run successfully.
