### ISSUE TITLE
Trailing white space in "activemq.brokerIp" causes exceptions

### ISSUE THREAD

**Issue by KLuka** [openbaton/NFVO#9]
From attached log we can see that configuration parameter `activemq.brokerIp` from `/etc/openbaton/openbaton.properties` is not striped of trailing white spaces before being used.

IMO white space trimming would make the application more robust. What do you think?

```
Caused by: java.net.URISyntaxException: Illegal character in authority at index 6: tcp://192.168.26.58 :61616
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.parseAuthority(URI.java:3167)
        at java.net.URI$Parser.parseHierarchical(URI.java:3078)
        at java.net.URI$Parser.parse(URI.java:3034)
        at java.net.URI.<init>(URI.java:595)
        at org.apache.activemq.ActiveMQConnectionFactory.createURI(ActiveMQConnectionFactory.java:234)
        ... 70 common frames omitted
```

**Comment by KLuka** [comment]
The same problem is present in version **0.15** with `nfvo.rabbit.brokerIp` parameter.

**Comment by gc4rella** [comment]
could you please let us know what are those problems?

**Comment by KLuka** [comment]
I tested this again and it works OK now :+1: I think I had some other issues before, sorry about that.
